### ISSUE TITLE
这个怎么用呢在laravel中，我有点不明白

### ISSUE THREAD

**Issue by boneq** [limen/redmodel#1]
这个怎么用呢在laravel中，我有点不明白

**Comment by limen** [comment]
这个包不是专门用于laravel的，只是借鉴了laravel model的风格。可以用于任何php版本高于5.4的工程。

**Comment by ghost** [comment]
这个很不错.我喜欢!最近需要做一个像这样的的API 还不知道怎么下手,看来您的感觉似乎明白了一些

**Comment by limen** [comment]
update：支持PHP 5.5及以上版本。

**Comment by geekxz** [comment]
老铁为何我用thinkphp引入完全没有配置成功报错
