### ISSUE TITLE
不支持事务么

### ISSUE THREAD

**Issue by renhonghai** [limen/redmodel#2]
如题

**Comment by limen** [comment]
redis对请求的处理是串行的，不存在并发冲突，所以redis本身是不支持事务的。

**Comment by miaojihao** [comment]
是否支持模糊搜索，像sql中的like一样可以模糊检索关键词

**Comment by limen** [comment]
@miaojihao 对这个库的定位还是存在一定的误解，这个库没有增强redis的功能，例如是否支持事务，是否支持like查询，这需要去了解redis本身是否支持。提供类sql的查询方式主要用来拼接key，例如where，whereIn。统一的操作命令是为了降低redis使用的复杂度，例如list|hash|set均可以通过get获取，而不需要根据类型选择使用lrange | hmget | smembers。
